name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
    - name: Make Python script executable
      run: chmod +x rank.py
    - name: Run Selenium script
      run: python3 rank.py
    - name: Commit any changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add .
        git commit -m "Add generated CSV files" -a || echo "No changes to commit"
    - name: Pull with rebase
      run: git pull --rebase origin main
    - name: Push changes using PAT
      run: git push https://${{ secrets.RANK }}@github.com/TreeCityWes/X1-Validator-Scrape.git HEAD:main
