name: Python application

on:
  schedule:
    - cron: '*/10 * * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
        # Replace the below line with any additional dependencies you have
        # pip install -r requirements.txt
    - name: Run Selenium script
      run: python your-script-name.py
    # Remove lint and test steps if not applicable
    # - name: Lint with flake8
    #   run: |
    #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest
