name: Python Application Automation

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your required Python version

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium  # Add other dependencies if necessary

    - name: Run Python Script
      run: python rank.py  # Replace with your script name if different

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f *.csv
        git commit -m "Update CSV files" -a || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.VALIDATOR }}
