name: Python application

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium webdriver_manager
    - name: Make Python script executable
      run: chmod +x rank.py
    - name: Run Selenium script
      run: python3 rank.py  # Changed to execute the script directly
    - name: Commit CSV files
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add *.csv
        git commit -m "Add generated CSV files" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.RANK }}  # Make sure this matches your PAT name
        branch: 'main'
